remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Tatooine
logo: /assets/img/github-mark/github-mark/github-mark.svg
description: Desert planet
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
